wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721756523
    t:
      1:
      - 55
      - 86
      - 92
      - 95
      - 96
      - 105
      2:
      - 55
      - 86
      - 92
      - 95
      - 96
      - 105
      3:
      - 2
      - 23
      4: 3.10.12
      5: 0.17.5
      8:
      - 5
      13: linux-x86_64
